alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias gs='git status'
alias gaa='git add -A'
alias gcv='git commit -v'
alias gp='git push'
alias gpm='git pull origin master'
alias gdiff='git diff --staging'
alias pullreqs='firefox https://github.com/pulls'
alias _alias='vi ~/bash_aliases'
alias _reload='source ~/.bashrc'
alias _dow='cd ~/Downloads'
shebang() {
   touch $1
   echo '#!/usr/bin/env bash' > $1
   vi $1
}
freshMaster() {
  git checkout master
  git pull origin master
}
newfeaturebranch(){
  freshMaster
  git checkout -b feature/$1
}
gpsu(){
  current_branch="$(git branch | grep \* | awk '{print $2}')"
  git push --set-upstream origin "$current_branch"
}
_gcv(){
  current_branch="$(git branch | grep \* | awk '{print $2}')"
  echo "$current_branch"

  IFS='/'        # space is set as delimiter
  read -ra ADDR <<< "$current_branch"    # str is read into an array as tokens separated by IFS
  task_number="${ADDR[1]}"
  git commit -v -m "ref $task_number," -e
}
